spring:
  application:
    name: configserver
  profiles:
    active:
      # - native
      - git
  cloud:
    config:
      server:
        # native:
        #   search-locations:
        #     - "classpath:/config"
        git:
          uri: <your-git-repository-uri>
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
